### ISSUE TITLE
Reduce a number of external dependencies

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/aiida-crystal#2]
Do we really need `ejplugins` and `pymatgen`?

**Comment by blokhin** [comment]
Given the code is PY3-only, why `six` is needed?

**Comment by ansobolev** [comment]
About `ejplugins` and `pymatgen`: these are also remnants of the old code base, now deleted.
About `six`: the code is both PY2 and Py3 compatible, please see Travis CI configuration

**Comment by blokhin** [comment]
`pymatgen` is still in `travis.yml`

**Comment by blokhin** [comment]
`ejplugins` is still in `aiida_crystal/io/out.py` and in `aiida_crystal/parsers/migrate.py`

**Comment by ansobolev** [comment]
`pymatgen` in `travis.yml` has been commented out since 01.03; however, string deleted. All `ejplugins` files are from the old code base, now also deleted
