### ISSUE TITLE
Not a best practice of the MPDS usage

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/aiida-crystal#3]
Please avoid caching MPDS data into `entries.csv` and reading using `ast.literal_eval`. Moreover, the API key can be stored relatively securely in a user shell environment. Although CI usage is inapplicable in this particular case, a user should be able to test MPDS retrieval on his own machine with his own API key.

**Comment by ansobolev** [comment]
All the work on structures is now done in the [`mpds-aiida`](https://github.com/mpds-io/mpds-aiida) workflow; `MPDS_KEY` is now read from the environment variables.
